name: gismultiinstancetestingenvironment
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  geolocator: ^13.0.2
  html: ^0.15.5
  http: ^1.3.0
  latlong2: ^0.9.1
  mapbox_maps_flutter: ^2.6.0
  supabase_flutter: ^2.8.3
  webview_flutter: ^4.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter: 
  uses-material-design: true
  assets:
  - assets/.env
  - assets/captcha.html
