// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'firebase_options.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart

/// // ...
//await Firebase.initializeApp(
// options: DefaultFirebaseOptions.currentPlatform,
//);
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD83681vLMnHNnxaTReOyoKP7PZgejIf0U',
    appId: '1:432218992295:web:04acc871ba334c61d7f582',
    messagingSenderId: '432218992295',
    projectId: 'gismauth',
    authDomain: 'gismauth.firebaseapp.com',
    storageBucket: 'gismauth.firebasestorage.app',
    measurementId: 'G-JE7R79F15D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrkO4ovvhLpAGig7-_KUs5yenysSTjlIg',
    appId: '1:432218992295:android:be725bb5b9279774d7f582',
    messagingSenderId: '432218992295',
    projectId: 'gismauth',
    storageBucket: 'gismauth.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmTzIkE--4j0FU_DSuNj0h2wCPcz9gKy4',
    appId: '1:432218992295:ios:5b0fcd6877d6b7aad7f582',
    messagingSenderId: '432218992295',
    projectId: 'gismauth',
    storageBucket: 'gismauth.firebasestorage.app',
    iosBundleId: 'com.example.gismultiinstancetestingenvironment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmTzIkE--4j0FU_DSuNj0h2wCPcz9gKy4',
    appId: '1:432218992295:ios:5b0fcd6877d6b7aad7f582',
    messagingSenderId: '432218992295',
    projectId: 'gismauth',
    storageBucket: 'gismauth.firebasestorage.app',
    iosBundleId: 'com.example.gismultiinstancetestingenvironment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD83681vLMnHNnxaTReOyoKP7PZgejIf0U',
    appId: '1:432218992295:web:9ef90b5f06fbd52cd7f582',
    messagingSenderId: '432218992295',
    projectId: 'gismauth',
    authDomain: 'gismauth.firebaseapp.com',
    storageBucket: 'gismauth.firebasestorage.app',
    measurementId: 'G-JG5CLVD15H',
  );
}
